[mypy]
python_version = 3.12
ignore_missing_imports = True
exclude = (?x)(
    tests/ |
    src/cks/cli/ |
    src/cks/adapters/ |
    src/cks/plugin\.py |
    src/cks/engine\.py |
    src/cks/interface\.py |
    src/cks/diagnostics\.py |
    src/cks/result\.py
    )

[mypy-cks.core.*]
strict = True

[mypy-cks.constraints.*]
strict = True

[mypy-cks.serialization.*]
strict = True

[mypy-cks.validator.*]
strict = True